services:
  backend:
    build:
      context: ./backend
    container_name: mon_backend
    ports:
      - "3001:3001"

  nginx:
    image : nginx:alpine
    container_name: nginx
    volumes : 
      - ./nginx/defaut.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/:/usr/share/nginx/html/    
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
